new
    account_id[MAX_PLAYERS],
    account_password[MAX_PLAYERS][64],
    
    player_login_attempts[MAX_PLAYERS],
    
    char_id[MAX_PLAYERS],
    char_score[MAX_PLAYERS],
    char_money[MAX_PLAYERS],
    char_skin[MAX_PLAYERS],
    char_admin[MAX_PLAYERS],
    char_admin_code[MAX_PLAYERS],

    char_warn_num[MAX_PLAYERS] = 0,
    
    char_muted[MAX_PLAYERS],
    char_muted_mins[MAX_PLAYERS];